apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: rhods-fraud-detection
    team: opendatahub
  name: fraud
  namespace: bk-models
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: http
  selector:
    matchLabels:
      app: rhods-fraud-detection
