---
kind: Secret
apiVersion: v1
metadata:
  name: aws-credentials
data:
  AWS_ACCESS_KEY: <insert your Amazon access key Base64 encoded string>
  AWS_SECRET_KEY: <insert your Amazon secret key Base64 encoded string>
type: Opaque
